### ISSUE TITLE
[Bug] Concurrency error in TeePee.Refit

### ISSUE THREAD

**Issue by oatsoda** [oatsoda/TeePee#44]
```
  Error Message:
   System.InvalidOperationException : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
  Stack Trace:
     at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at TeePee.Refit.ServiceCollectionExtensions.GetRefitHttpFactoryName[T]()
   at TeePee.Refit.ServiceCollectionExtensions.AttachToRefitInterface[TRefitInterface](IServiceCollection serviceCollection, TeePee teePee)
```

**Comment by oatsoda** [comment]
Fix via https://github.com/oatsoda/TeePee/commit/227855a40fd1ed01ef407eaa34a59595f864e717
